export default {
    adenovirus: 'Adenovirus',
    anthrax: 'Anthrax',
    cholera: 'Cholera',
    diphtheria: 'Diphtheria',
    hepA: 'Hepatitis A',
    hepB: 'Hepatitis B',
    hib: 'Haemophilus influenza type b (Hib)',
    hpv: 'Human Papillomavirus (HPV)',
    flu: 'Seasonal Influenza (Flu)',
    japanese_encephalitis: 'Japanese Encephalitis',
    measles: 'Measles',
    meningococcal: 'Meningoccal',
    mumps: 'Mumps',
    pertussis: 'Pertussis',
    pneumococcal: 'Pneumococcal',
    polio: 'Polio',
    rabies: 'Rabies',
    rotavirus: 'Rotavirus',
    rubella: 'Rubella',
    shingles: 'Shingles',
    smallpox: 'Smallpox',
    tetanus: 'Tetanus',
    tuberculosis: 'Tuberculosis',
    typhoid_fever: 'Typhoid Fever',
    varicella: 'Varicella',
    yellow_fever: 'Yellow Fever'
}
