export default [
    "adenovirus",
    "anthrax",
    "cholera",
    "diphtheria",
    "hepA",
    "hepB",
    "hib",
    "hpv",
    "flu",
    "japanese_encephalitis",
    "measles",
    "meningococcal",
    "mumps",
    "pertussis",
    "pneumococcal",
    "polio",
    "rabies",
    "rotavirus",
    "rubella",
    "shingles",
    "smallpox",
    "tetanus",
    "tuberculosis",
    "typhoid fever",
    "varicella",
    "yellow_fever"
]